name = "wg-debugging"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["pnkfelix", "wesleywiser"]
members = [
    "davidtwco",
    "pnkfelix",
    "wesleywiser",
]
alumni = [
    "Manishearth",
    "michaelwoerister",
]

[website]
name = "Debugging Working Group"
description = "Providing users with a great experience when debugging Rust code"
zulip-stream = "t-compiler/wg-debugging"

[[github]]
orgs = ["rust-lang"]
