name = "wg-parallel-rustc"
subteam-of = "compiler"
wg = true

[people]
leads = ["Zoxc", "aturon"]
members = ["Zoxc", "aturon"]

[website]
name = "Parallel rustc"
description = "Making parallel compilation the default for rustc"
repo = "https://rust-lang.github.io/compiler-team/working-groups/parallel-rustc/"
